# Generated by Django 6.0.3 on 2026-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacteurEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('coefficient', models.FloatField()),
            ],
        ),
    ]
