# Generated by Django 6.0.3 on 2026-05-05 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanCarbone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=7)),
                ('total_co2', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='LigneCarbone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=255)),
                ('consommation', models.FloatField(default=0)),
                ('co2', models.FloatField(default=0)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounts.bilancarbone')),
            ],
        ),
    ]
