# Generated by Django 6.0.3 on 2026-06-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bilancarbone_lignecarbone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('Energie', 'Energie'), ('Mobilité', 'Mobilité'), ('Déchets', 'Déchets'), ('Alimentation', 'Alimentation'), ('Numérique', 'Numérique'), ('Achats', 'Achats'), ('Bâtiments', 'Bâtiments'), ('Logistique', 'Logistique'), ('Climat', 'Climat'), ('Eau', 'Eau'), ('Biodiversité', 'Biodiversité')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gain_co2', models.FloatField(default=0)),
                ('cout', models.CharField(blank=True, max_length=100)),
                ('delai', models.CharField(blank=True, max_length=100)),
                ('priorite', models.CharField(blank=True, max_length=50)),
                ('financement', models.CharField(blank=True, max_length=255)),
                ('indicateur', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
