# Generated by Django 6.0.3 on 2026-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_actiontransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='facteuremission',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facteuremission',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facteuremission',
            name='source',
            field=models.CharField(default='Base Empreinte® ADEME – sélection VertClair', max_length=255),
        ),
        migrations.AddField(
            model_name='facteuremission',
            name='unite',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
