# Generated by Django 6.0.3 on 2026-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_facteuremission_actif_facteuremission_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facteuremission',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facteuremission',
            name='unite',
            field=models.CharField(max_length=50),
        ),
    ]
