# Generated by Django 6.0.3 on 2026-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_resultatquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontransition',
            name='financements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actiontransition',
            name='indicateur_suivi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actiontransition',
            name='objectifs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actiontransition',
            name='sources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actiontransition',
            name='valeur_cible',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
