# Generated by Django 6.0.3 on 2026-06-29 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_actiontransition_financements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_organisation', models.CharField(choices=[('commune', 'Commune / collectivité'), ('entreprise', 'Entreprise'), ('association', 'Association'), ('particulier', 'Particulier'), ('autre', 'Autre')], default='entreprise', max_length=50)),
                ('siret', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(max_length=100)),
                ('nb_licences', models.PositiveIntegerField(default=1)),
                ('prix_mensuel_ht', models.DecimalField(decimal_places=2, default=35, max_digits=8)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('essai', 'Période d’essai'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié'), ('expire', 'Expiré')], default='essai', max_length=30)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=30)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='accounts.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_vertclair', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
