# Generated by Django 6.0.3 on 2026-06-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organisation_abonnement_profilutilisateur'),
    ]

    operations = [
    ]
