# Generated by Django 6.0.3 on 2026-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_saas_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('fenny', 'Fenny - Superviseur global'), ('admin_org', 'Administrateur d’organisation'), ('gestionnaire', 'Gestionnaire'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=30),
        ),
    ]
