# Generated by Django 6.0.3 on 2026-06-29 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_serviceorganisation_profilutilisateur_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('fenny', 'Fenny - Superviseur global'), ('admin_org', 'Administrateur d’organisation'), ('gestionnaire', 'Gestionnaire'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=30)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('acceptee', models.BooleanField(default=False)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('invite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organisation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.serviceorganisation')),
            ],
        ),
    ]
