# Generated by Django 6.0.3 on 2026-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_invitationutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationutilisateur',
            name='role',
            field=models.CharField(choices=[('fenny', 'Fenny - Superviseur global'), ('admin_org', 'Administrateur d’organisation'), ('gestionnaire', 'Gestionnaire'), ('utilisateur', 'Utilisateur'), ('lecteur', 'Lecteur')], default='utilisateur', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('fenny', 'Fenny - Superviseur global'), ('admin_org', 'Administrateur d’organisation'), ('gestionnaire', 'Gestionnaire'), ('utilisateur', 'Utilisateur'), ('lecteur', 'Lecteur')], default='utilisateur', max_length=30),
        ),
    ]
