# Generated by Django 6.0.3 on 2026-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_invitationutilisateur_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='formule',
            field=models.CharField(choices=[('essai', 'Essai'), ('1', '1 utilisateur'), ('5', '5 utilisateurs'), ('10', '10 utilisateurs'), ('20', '20 utilisateurs'), ('50', '50 utilisateurs'), ('100', '100 utilisateurs')], default='essai', max_length=30),
        ),
    ]
