# Generated by Django 6.0.3 on 2026-06-30 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_abonnement_formule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('invitation_envoyee', 'Invitation envoyée'), ('invitation_acceptee', 'Invitation acceptée'), ('utilisateur_modifie', 'Utilisateur modifié'), ('utilisateur_desactive', 'Utilisateur désactivé'), ('utilisateur_reactive', 'Utilisateur réactivé'), ('abonnement_modifie', 'Abonnement modifié')], max_length=50)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_activite', to='accounts.organisation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_vertclair', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
